# This is a config for E2B sandbox template.
# You can use template ID (0szqhsrgikxynzgu09xv) or template name (vite-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vite-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("vite-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vite-template')

team_id = "35f2ed91-a6af-4e6c-a693-9e9e244fcdbd"
dockerfile = "e2b.Dockerfile"
template_name = "vite-template"
template_id = "0szqhsrgikxynzgu09xv"
