# This is a config for E2B sandbox template.
# You can use template ID (e9devag07oqgiyid3zox) or template name (vue-dynamic-sandbox) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vue-dynamic-sandbox") # Sync sandbox
# sandbox = await AsyncSandbox.create("vue-dynamic-sandbox") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vue-dynamic-sandbox')

team_id = "35f2ed91-a6af-4e6c-a693-9e9e244fcdbd"
dockerfile = "e2b.Dockerfile"
template_name = "vue-dynamic-sandbox"
template_id = "e9devag07oqgiyid3zox"
